"""initial schema

Revision ID: 5027e3ba87c7
Revises: 
Create Date: 2025-12-29 19:27:51.022984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5027e3ba87c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_tags_id'), 'error_tags', ['id'], unique=False)
    op.create_index(op.f('ix_error_tags_name'), 'error_tags', ['name'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('canonical_form', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_canonical_form'), 'items', ['canonical_form'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_type'), 'items', ['type'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_id'), 'edges', ['id'], unique=False)
    op.create_index(op.f('ix_edges_relation_type'), 'edges', ['relation_type'], unique=False)
    op.create_index(op.f('ix_edges_source_id'), 'edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_edges_target_id'), 'edges', ['target_id'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('actual_answer', sa.Text(), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('confusion_target_id', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confusion_target_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_correct'), 'encounters', ['correct'], unique=False)
    op.create_index(op.f('ix_encounters_error_type'), 'encounters', ['error_type'], unique=False)
    op.create_index(op.f('ix_encounters_id'), 'encounters', ['id'], unique=False)
    op.create_index(op.f('ix_encounters_item_id'), 'encounters', ['item_id'], unique=False)
    op.create_index(op.f('ix_encounters_mode'), 'encounters', ['mode'], unique=False)
    op.create_index(op.f('ix_encounters_timestamp'), 'encounters', ['timestamp'], unique=False)
    # ### end Alembic commands ###

    # Seed error taxonomy from PRD Section 4.2
    error_tags = [
        ('GENDER_der_die', 'Masculine/feminine gender confusion'),
        ('GENDER_der_das', 'Masculine/neuter gender confusion'),
        ('GENDER_die_das', 'Feminine/neuter gender confusion'),
        ('CASE_nom_akk', 'Nominative/Accusative case confusion'),
        ('CASE_akk_dat', 'Accusative/Dative case confusion'),
        ('CASE_dat_gen', 'Dative/Genitive case confusion'),
        ('PREP_CASE', 'Incorrect case following a preposition'),
        ('WORD_ORDER_verb_final', 'Failure to place verb at end of subordinate clause'),
        ('WORD_ORDER_inversion', 'Failure to invert subject/verb after fronted element'),
        ('VERB_FORM_conjugation', 'Incorrect verb ending for person/number'),
        ('VERB_FORM_participle', 'Incorrect past participle form'),
        ('VERB_FORM_auxiliary', 'Confusion between haben and sein in Perfekt'),
        ('VERB_FORM_tense', 'Incorrect tense selected for context'),
        ('ADJECTIVE_ENDING', 'Incorrect adjective declension'),
        ('COLLOCATION', 'Unnatural word combination'),
        ('CONFUSABLE', 'Semantic confusion between similar words'),
        ('LEXICAL', 'Incorrect word choice not covered by other categories'),
    ]

    for name, description in error_tags:
        op.execute(
            f"INSERT INTO error_tags (name, description) VALUES ('{name}', '{description}')"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encounters_timestamp'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_mode'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_item_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_error_type'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_correct'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_edges_target_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_source_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_relation_type'), table_name='edges')
    op.drop_index(op.f('ix_edges_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_items_type'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_canonical_form'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_error_tags_name'), table_name='error_tags')
    op.drop_index(op.f('ix_error_tags_id'), table_name='error_tags')
    op.drop_table('error_tags')
    # ### end Alembic commands ###
